### ISSUE TITLE
As a player, I want a more colorful paddles

### ISSUE THREAD

**Issue by immd** [leesanhoon/Assignment-4#20]
1. Lên Internet tìm thông tin: 15 phút
2. Cập nhật gitHub để xem nhiệm vụ: 5 phút
3. Eclipse để bổ sung thực hiện các yêu cầu đã đặt ra và push: 30 phút
4. Kiểm tra việc thực hiện trên github: 5 phút
Sum:  60 phút

**Comment by hokage96qn** [comment]
tìm hiểu 1h
Thực hiện: 2h
Sửa chữa: 30p
Tổng: 3h30p.
