### ISSUE TITLE
As a player, I want to be able to set my name and show it on screen

### ISSUE THREAD

**Issue by leesanhoon** [leesanhoon/Assignment-4#22]

**Comment by leesanhoon** [comment]
Nghiên cứu :20'
Viết code và kiểm ra 1h
Tổng :1h20'

**Comment by immd** [comment]
tìm hiểu : 1h
code : 2h
Chỉnh sửa: 30"
Tổng 3h30"

**Comment by immd** [comment]
tìm hiểu : 1h
code : 1h
Chỉnh sửa: 30"
Tổng 2h30"
